# Generated by Django 5.2.12 on 2026-04-01 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiLimiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "speed_value",
                    models.CharField(
                        help_text="Provide the value in requests/second, such as: 5, 10, 20...",
                        max_length=100,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "Get"),
                            ("POST", "Post"),
                            ("DELETE", "Delete"),
                            ("PATCH", "Patch"),
                            ("PUT", "Put"),
                            ("HEAD", "Head"),
                            ("OPTIONS", "Options"),
                        ]
                    ),
                ),
                ("url", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="UserSpecificLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "speed_value",
                    models.CharField(
                        help_text="Provide the value in requests/second, such as: 5, 10, 20...",
                        max_length=100,
                    ),
                ),
                (
                    "affected_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "api_limiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_limiter.apilimiter",
                    ),
                ),
            ],
        ),
    ]
